### ISSUE TITLE
Not working on Android 10 (Galaxy S9+)

### ISSUE THREAD

**Issue by rodrigopiccelli** [r3bl-alliance/stay-awake-app#11] opened 2020-07-02 16:05 UTC
App don't work on Android 10 on Samsung Galaxy S9+

**Comment by fkubicek** [comment] 2020-07-06 21:59
Hello, could you please specify what isn't working for you? I have noticed problems with the automatic start when the charger is plugged in - Awake just doesn't start automatically. Are you referring to this?

**Comment by rodrigopiccelli** [comment] 2020-07-07 06:20
Unfortunately not ... the application simply does not do its function, even enabling the option to keep the screen on it continues to shut down normally.

I'm on a Galaxy S9+ with Android 10 on it.

**Comment by fkubicek** [comment] 2020-07-07 07:21
Oh, I see. Thanks for clearing that up. It may be caused by Samsung's changes to the OS, because it seems to work on clean Android 10. I would try making an exception for Awake, if your system has a background process killer. This is my best guess.

Unfortunately I can't help any further, because I don't know much about the backend. @nazmulidris said he was planning to rewrite parts of the app, so it could get fixed in the process.

**Closed as completed** 2020-08-10 23:20 UTC
